spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 807327124723-k2hvh6cm0heein1pf7fg0nclspm0urkj.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:gallery_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
    hibernate:
      ddl-auto: update

server:
  port: 18181
  servlet:
    context-path: /gallery
