spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 807327124723-k2hvh6cm0heein1pf7fg0nclspm0urkj.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:gallery_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
    hibernate:
      ddl-auto: update

server:
  port: 18181
  servlet:
    context-path: /gallery

upload:
  use-application-home: true
  path: uploads
  filename:
    unknown: (uknown)
    format: "%1$s-%2$d.%3$s"
    randomizer-limit: 1000000
    timestamp:
      format: yyyyMMddHmmssSSS
      time-zone: UTC

